name: Docker

on:
  push:
    branches: ["master"]
    paths:
     - "docker/**"
     - ".github/workflows/docker.yml"
     - "scripts/build_docker_image.py"
  pull_request:
    branches: ["master"]
    paths:
     - "docker/**"
     - ".github/workflows/docker.yml"
     - "scripts/build_docker_image.py"

jobs:
  build-docker-image:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: jlumbroso/free-disk-space@main
        with:
          docker-images: false

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Build Docker Image
        run: python -m scripts.build_docker_image --verbose
